// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.178.0
//   protoc               unknown
// source: model/v1/events.proto

/* eslint-disable */
import * as _m0 from "protobufjs/minimal";

export const protobufPackage = "model.v1";

export interface BlockEvent {
  blockHash: string;
  blockNumber: string;
  network: BlockEvent_Network | undefined;
  block: BlockEvent_Block | undefined;
}

export interface BlockEvent_Network {
  chainId: string;
}

export interface BlockEvent_Block {
  difficulty: string;
  extraData: string;
  gasLimit: string;
  gasUsed: string;
  hash: string;
  logsBloom: string;
  miner: string;
  mixHash: string;
  nonce: string;
  number: string;
  parentHash: string;
  receiptsRoot: string;
  sha3Uncles: string;
  size: string;
  stateRoot: string;
  timestamp: string;
  totalDifficulty: string;
  transactions: string[];
  transactionsRoot: string;
  uncles: string[];
  baseFeePerGas: string;
}

export interface TransactionEvent {
  transaction: TransactionEvent_Transaction | undefined;
  network: TransactionEvent_Network | undefined;
  addresses: { [key: string]: boolean };
  block: TransactionEvent_Block | undefined;
  logs: TransactionEvent_Log[];
  isContractDeployment: boolean;
  contractAddress: string;
  txAddresses: { [key: string]: boolean };
}

export interface TransactionEvent_Network {
  chainId: string;
}

export interface TransactionEvent_Block {
  blockHash: string;
  blockNumber: string;
  blockTimestamp: string;
  baseFeePerGas: string;
}

export interface TransactionEvent_Transaction {
  type: string;
  nonce: string;
  gasPrice: string;
  gas: string;
  value: string;
  input: string;
  v: string;
  r: string;
  s: string;
  to: string;
  hash: string;
  from: string;
  maxFeePerGas: string;
  maxPriorityFeePerGas: string;
}

export interface TransactionEvent_Log {
  address: string;
  topics: string[];
  data: string;
  blockNumber: string;
  transactionHash: string;
  transactionIndex: string;
  blockHash: string;
  logIndex: string;
  removed: boolean;
}

export interface TransactionEvent_AddressesEntry {
  key: string;
  value: boolean;
}

export interface TransactionEvent_TxAddressesEntry {
  key: string;
  value: boolean;
}

function createBaseBlockEvent(): BlockEvent {
  return { blockHash: "", blockNumber: "", network: undefined, block: undefined };
}

export const BlockEvent = {
  encode(message: BlockEvent, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.blockHash !== "") {
      writer.uint32(10).string(message.blockHash);
    }
    if (message.blockNumber !== "") {
      writer.uint32(18).string(message.blockNumber);
    }
    if (message.network !== undefined) {
      BlockEvent_Network.encode(message.network, writer.uint32(26).fork()).ldelim();
    }
    if (message.block !== undefined) {
      BlockEvent_Block.encode(message.block, writer.uint32(34).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): BlockEvent {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseBlockEvent();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.blockHash = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.blockNumber = reader.string();
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.network = BlockEvent_Network.decode(reader, reader.uint32());
          continue;
        case 4:
          if (tag !== 34) {
            break;
          }

          message.block = BlockEvent_Block.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): BlockEvent {
    return {
      blockHash: isSet(object.blockHash) ? globalThis.String(object.blockHash) : "",
      blockNumber: isSet(object.blockNumber) ? globalThis.String(object.blockNumber) : "",
      network: isSet(object.network) ? BlockEvent_Network.fromJSON(object.network) : undefined,
      block: isSet(object.block) ? BlockEvent_Block.fromJSON(object.block) : undefined,
    };
  },

  toJSON(message: BlockEvent): unknown {
    const obj: any = {};
    if (message.blockHash !== "") {
      obj.blockHash = message.blockHash;
    }
    if (message.blockNumber !== "") {
      obj.blockNumber = message.blockNumber;
    }
    if (message.network !== undefined) {
      obj.network = BlockEvent_Network.toJSON(message.network);
    }
    if (message.block !== undefined) {
      obj.block = BlockEvent_Block.toJSON(message.block);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<BlockEvent>, I>>(base?: I): BlockEvent {
    return BlockEvent.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<BlockEvent>, I>>(object: I): BlockEvent {
    const message = createBaseBlockEvent();
    message.blockHash = object.blockHash ?? "";
    message.blockNumber = object.blockNumber ?? "";
    message.network = (object.network !== undefined && object.network !== null)
      ? BlockEvent_Network.fromPartial(object.network)
      : undefined;
    message.block = (object.block !== undefined && object.block !== null)
      ? BlockEvent_Block.fromPartial(object.block)
      : undefined;
    return message;
  },
};

function createBaseBlockEvent_Network(): BlockEvent_Network {
  return { chainId: "" };
}

export const BlockEvent_Network = {
  encode(message: BlockEvent_Network, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.chainId !== "") {
      writer.uint32(10).string(message.chainId);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): BlockEvent_Network {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseBlockEvent_Network();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.chainId = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): BlockEvent_Network {
    return { chainId: isSet(object.chainId) ? globalThis.String(object.chainId) : "" };
  },

  toJSON(message: BlockEvent_Network): unknown {
    const obj: any = {};
    if (message.chainId !== "") {
      obj.chainId = message.chainId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<BlockEvent_Network>, I>>(base?: I): BlockEvent_Network {
    return BlockEvent_Network.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<BlockEvent_Network>, I>>(object: I): BlockEvent_Network {
    const message = createBaseBlockEvent_Network();
    message.chainId = object.chainId ?? "";
    return message;
  },
};

function createBaseBlockEvent_Block(): BlockEvent_Block {
  return {
    difficulty: "",
    extraData: "",
    gasLimit: "",
    gasUsed: "",
    hash: "",
    logsBloom: "",
    miner: "",
    mixHash: "",
    nonce: "",
    number: "",
    parentHash: "",
    receiptsRoot: "",
    sha3Uncles: "",
    size: "",
    stateRoot: "",
    timestamp: "",
    totalDifficulty: "",
    transactions: [],
    transactionsRoot: "",
    uncles: [],
    baseFeePerGas: "",
  };
}

export const BlockEvent_Block = {
  encode(message: BlockEvent_Block, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.difficulty !== "") {
      writer.uint32(10).string(message.difficulty);
    }
    if (message.extraData !== "") {
      writer.uint32(18).string(message.extraData);
    }
    if (message.gasLimit !== "") {
      writer.uint32(26).string(message.gasLimit);
    }
    if (message.gasUsed !== "") {
      writer.uint32(34).string(message.gasUsed);
    }
    if (message.hash !== "") {
      writer.uint32(42).string(message.hash);
    }
    if (message.logsBloom !== "") {
      writer.uint32(50).string(message.logsBloom);
    }
    if (message.miner !== "") {
      writer.uint32(58).string(message.miner);
    }
    if (message.mixHash !== "") {
      writer.uint32(66).string(message.mixHash);
    }
    if (message.nonce !== "") {
      writer.uint32(74).string(message.nonce);
    }
    if (message.number !== "") {
      writer.uint32(82).string(message.number);
    }
    if (message.parentHash !== "") {
      writer.uint32(90).string(message.parentHash);
    }
    if (message.receiptsRoot !== "") {
      writer.uint32(98).string(message.receiptsRoot);
    }
    if (message.sha3Uncles !== "") {
      writer.uint32(106).string(message.sha3Uncles);
    }
    if (message.size !== "") {
      writer.uint32(114).string(message.size);
    }
    if (message.stateRoot !== "") {
      writer.uint32(122).string(message.stateRoot);
    }
    if (message.timestamp !== "") {
      writer.uint32(130).string(message.timestamp);
    }
    if (message.totalDifficulty !== "") {
      writer.uint32(138).string(message.totalDifficulty);
    }
    for (const v of message.transactions) {
      writer.uint32(146).string(v!);
    }
    if (message.transactionsRoot !== "") {
      writer.uint32(154).string(message.transactionsRoot);
    }
    for (const v of message.uncles) {
      writer.uint32(162).string(v!);
    }
    if (message.baseFeePerGas !== "") {
      writer.uint32(170).string(message.baseFeePerGas);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): BlockEvent_Block {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseBlockEvent_Block();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.difficulty = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.extraData = reader.string();
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.gasLimit = reader.string();
          continue;
        case 4:
          if (tag !== 34) {
            break;
          }

          message.gasUsed = reader.string();
          continue;
        case 5:
          if (tag !== 42) {
            break;
          }

          message.hash = reader.string();
          continue;
        case 6:
          if (tag !== 50) {
            break;
          }

          message.logsBloom = reader.string();
          continue;
        case 7:
          if (tag !== 58) {
            break;
          }

          message.miner = reader.string();
          continue;
        case 8:
          if (tag !== 66) {
            break;
          }

          message.mixHash = reader.string();
          continue;
        case 9:
          if (tag !== 74) {
            break;
          }

          message.nonce = reader.string();
          continue;
        case 10:
          if (tag !== 82) {
            break;
          }

          message.number = reader.string();
          continue;
        case 11:
          if (tag !== 90) {
            break;
          }

          message.parentHash = reader.string();
          continue;
        case 12:
          if (tag !== 98) {
            break;
          }

          message.receiptsRoot = reader.string();
          continue;
        case 13:
          if (tag !== 106) {
            break;
          }

          message.sha3Uncles = reader.string();
          continue;
        case 14:
          if (tag !== 114) {
            break;
          }

          message.size = reader.string();
          continue;
        case 15:
          if (tag !== 122) {
            break;
          }

          message.stateRoot = reader.string();
          continue;
        case 16:
          if (tag !== 130) {
            break;
          }

          message.timestamp = reader.string();
          continue;
        case 17:
          if (tag !== 138) {
            break;
          }

          message.totalDifficulty = reader.string();
          continue;
        case 18:
          if (tag !== 146) {
            break;
          }

          message.transactions.push(reader.string());
          continue;
        case 19:
          if (tag !== 154) {
            break;
          }

          message.transactionsRoot = reader.string();
          continue;
        case 20:
          if (tag !== 162) {
            break;
          }

          message.uncles.push(reader.string());
          continue;
        case 21:
          if (tag !== 170) {
            break;
          }

          message.baseFeePerGas = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): BlockEvent_Block {
    return {
      difficulty: isSet(object.difficulty) ? globalThis.String(object.difficulty) : "",
      extraData: isSet(object.extraData) ? globalThis.String(object.extraData) : "",
      gasLimit: isSet(object.gasLimit) ? globalThis.String(object.gasLimit) : "",
      gasUsed: isSet(object.gasUsed) ? globalThis.String(object.gasUsed) : "",
      hash: isSet(object.hash) ? globalThis.String(object.hash) : "",
      logsBloom: isSet(object.logsBloom) ? globalThis.String(object.logsBloom) : "",
      miner: isSet(object.miner) ? globalThis.String(object.miner) : "",
      mixHash: isSet(object.mixHash) ? globalThis.String(object.mixHash) : "",
      nonce: isSet(object.nonce) ? globalThis.String(object.nonce) : "",
      number: isSet(object.number) ? globalThis.String(object.number) : "",
      parentHash: isSet(object.parentHash) ? globalThis.String(object.parentHash) : "",
      receiptsRoot: isSet(object.receiptsRoot) ? globalThis.String(object.receiptsRoot) : "",
      sha3Uncles: isSet(object.sha3Uncles) ? globalThis.String(object.sha3Uncles) : "",
      size: isSet(object.size) ? globalThis.String(object.size) : "",
      stateRoot: isSet(object.stateRoot) ? globalThis.String(object.stateRoot) : "",
      timestamp: isSet(object.timestamp) ? globalThis.String(object.timestamp) : "",
      totalDifficulty: isSet(object.totalDifficulty) ? globalThis.String(object.totalDifficulty) : "",
      transactions: globalThis.Array.isArray(object?.transactions)
        ? object.transactions.map((e: any) => globalThis.String(e))
        : [],
      transactionsRoot: isSet(object.transactionsRoot) ? globalThis.String(object.transactionsRoot) : "",
      uncles: globalThis.Array.isArray(object?.uncles) ? object.uncles.map((e: any) => globalThis.String(e)) : [],
      baseFeePerGas: isSet(object.baseFeePerGas) ? globalThis.String(object.baseFeePerGas) : "",
    };
  },

  toJSON(message: BlockEvent_Block): unknown {
    const obj: any = {};
    if (message.difficulty !== "") {
      obj.difficulty = message.difficulty;
    }
    if (message.extraData !== "") {
      obj.extraData = message.extraData;
    }
    if (message.gasLimit !== "") {
      obj.gasLimit = message.gasLimit;
    }
    if (message.gasUsed !== "") {
      obj.gasUsed = message.gasUsed;
    }
    if (message.hash !== "") {
      obj.hash = message.hash;
    }
    if (message.logsBloom !== "") {
      obj.logsBloom = message.logsBloom;
    }
    if (message.miner !== "") {
      obj.miner = message.miner;
    }
    if (message.mixHash !== "") {
      obj.mixHash = message.mixHash;
    }
    if (message.nonce !== "") {
      obj.nonce = message.nonce;
    }
    if (message.number !== "") {
      obj.number = message.number;
    }
    if (message.parentHash !== "") {
      obj.parentHash = message.parentHash;
    }
    if (message.receiptsRoot !== "") {
      obj.receiptsRoot = message.receiptsRoot;
    }
    if (message.sha3Uncles !== "") {
      obj.sha3Uncles = message.sha3Uncles;
    }
    if (message.size !== "") {
      obj.size = message.size;
    }
    if (message.stateRoot !== "") {
      obj.stateRoot = message.stateRoot;
    }
    if (message.timestamp !== "") {
      obj.timestamp = message.timestamp;
    }
    if (message.totalDifficulty !== "") {
      obj.totalDifficulty = message.totalDifficulty;
    }
    if (message.transactions?.length) {
      obj.transactions = message.transactions;
    }
    if (message.transactionsRoot !== "") {
      obj.transactionsRoot = message.transactionsRoot;
    }
    if (message.uncles?.length) {
      obj.uncles = message.uncles;
    }
    if (message.baseFeePerGas !== "") {
      obj.baseFeePerGas = message.baseFeePerGas;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<BlockEvent_Block>, I>>(base?: I): BlockEvent_Block {
    return BlockEvent_Block.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<BlockEvent_Block>, I>>(object: I): BlockEvent_Block {
    const message = createBaseBlockEvent_Block();
    message.difficulty = object.difficulty ?? "";
    message.extraData = object.extraData ?? "";
    message.gasLimit = object.gasLimit ?? "";
    message.gasUsed = object.gasUsed ?? "";
    message.hash = object.hash ?? "";
    message.logsBloom = object.logsBloom ?? "";
    message.miner = object.miner ?? "";
    message.mixHash = object.mixHash ?? "";
    message.nonce = object.nonce ?? "";
    message.number = object.number ?? "";
    message.parentHash = object.parentHash ?? "";
    message.receiptsRoot = object.receiptsRoot ?? "";
    message.sha3Uncles = object.sha3Uncles ?? "";
    message.size = object.size ?? "";
    message.stateRoot = object.stateRoot ?? "";
    message.timestamp = object.timestamp ?? "";
    message.totalDifficulty = object.totalDifficulty ?? "";
    message.transactions = object.transactions?.map((e) => e) || [];
    message.transactionsRoot = object.transactionsRoot ?? "";
    message.uncles = object.uncles?.map((e) => e) || [];
    message.baseFeePerGas = object.baseFeePerGas ?? "";
    return message;
  },
};

function createBaseTransactionEvent(): TransactionEvent {
  return {
    transaction: undefined,
    network: undefined,
    addresses: {},
    block: undefined,
    logs: [],
    isContractDeployment: false,
    contractAddress: "",
    txAddresses: {},
  };
}

export const TransactionEvent = {
  encode(message: TransactionEvent, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.transaction !== undefined) {
      TransactionEvent_Transaction.encode(message.transaction, writer.uint32(10).fork()).ldelim();
    }
    if (message.network !== undefined) {
      TransactionEvent_Network.encode(message.network, writer.uint32(18).fork()).ldelim();
    }
    Object.entries(message.addresses).forEach(([key, value]) => {
      TransactionEvent_AddressesEntry.encode({ key: key as any, value }, writer.uint32(26).fork()).ldelim();
    });
    if (message.block !== undefined) {
      TransactionEvent_Block.encode(message.block, writer.uint32(34).fork()).ldelim();
    }
    for (const v of message.logs) {
      TransactionEvent_Log.encode(v!, writer.uint32(42).fork()).ldelim();
    }
    if (message.isContractDeployment !== false) {
      writer.uint32(48).bool(message.isContractDeployment);
    }
    if (message.contractAddress !== "") {
      writer.uint32(58).string(message.contractAddress);
    }
    Object.entries(message.txAddresses).forEach(([key, value]) => {
      TransactionEvent_TxAddressesEntry.encode({ key: key as any, value }, writer.uint32(66).fork()).ldelim();
    });
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): TransactionEvent {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTransactionEvent();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.transaction = TransactionEvent_Transaction.decode(reader, reader.uint32());
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.network = TransactionEvent_Network.decode(reader, reader.uint32());
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          const entry3 = TransactionEvent_AddressesEntry.decode(reader, reader.uint32());
          if (entry3.value !== undefined) {
            message.addresses[entry3.key] = entry3.value;
          }
          continue;
        case 4:
          if (tag !== 34) {
            break;
          }

          message.block = TransactionEvent_Block.decode(reader, reader.uint32());
          continue;
        case 5:
          if (tag !== 42) {
            break;
          }

          message.logs.push(TransactionEvent_Log.decode(reader, reader.uint32()));
          continue;
        case 6:
          if (tag !== 48) {
            break;
          }

          message.isContractDeployment = reader.bool();
          continue;
        case 7:
          if (tag !== 58) {
            break;
          }

          message.contractAddress = reader.string();
          continue;
        case 8:
          if (tag !== 66) {
            break;
          }

          const entry8 = TransactionEvent_TxAddressesEntry.decode(reader, reader.uint32());
          if (entry8.value !== undefined) {
            message.txAddresses[entry8.key] = entry8.value;
          }
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): TransactionEvent {
    return {
      transaction: isSet(object.transaction) ? TransactionEvent_Transaction.fromJSON(object.transaction) : undefined,
      network: isSet(object.network) ? TransactionEvent_Network.fromJSON(object.network) : undefined,
      addresses: isObject(object.addresses)
        ? Object.entries(object.addresses).reduce<{ [key: string]: boolean }>((acc, [key, value]) => {
          acc[key] = Boolean(value);
          return acc;
        }, {})
        : {},
      block: isSet(object.block) ? TransactionEvent_Block.fromJSON(object.block) : undefined,
      logs: globalThis.Array.isArray(object?.logs) ? object.logs.map((e: any) => TransactionEvent_Log.fromJSON(e)) : [],
      isContractDeployment: isSet(object.isContractDeployment)
        ? globalThis.Boolean(object.isContractDeployment)
        : false,
      contractAddress: isSet(object.contractAddress) ? globalThis.String(object.contractAddress) : "",
      txAddresses: isObject(object.txAddresses)
        ? Object.entries(object.txAddresses).reduce<{ [key: string]: boolean }>((acc, [key, value]) => {
          acc[key] = Boolean(value);
          return acc;
        }, {})
        : {},
    };
  },

  toJSON(message: TransactionEvent): unknown {
    const obj: any = {};
    if (message.transaction !== undefined) {
      obj.transaction = TransactionEvent_Transaction.toJSON(message.transaction);
    }
    if (message.network !== undefined) {
      obj.network = TransactionEvent_Network.toJSON(message.network);
    }
    if (message.addresses) {
      const entries = Object.entries(message.addresses);
      if (entries.length > 0) {
        obj.addresses = {};
        entries.forEach(([k, v]) => {
          obj.addresses[k] = v;
        });
      }
    }
    if (message.block !== undefined) {
      obj.block = TransactionEvent_Block.toJSON(message.block);
    }
    if (message.logs?.length) {
      obj.logs = message.logs.map((e) => TransactionEvent_Log.toJSON(e));
    }
    if (message.isContractDeployment !== false) {
      obj.isContractDeployment = message.isContractDeployment;
    }
    if (message.contractAddress !== "") {
      obj.contractAddress = message.contractAddress;
    }
    if (message.txAddresses) {
      const entries = Object.entries(message.txAddresses);
      if (entries.length > 0) {
        obj.txAddresses = {};
        entries.forEach(([k, v]) => {
          obj.txAddresses[k] = v;
        });
      }
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<TransactionEvent>, I>>(base?: I): TransactionEvent {
    return TransactionEvent.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TransactionEvent>, I>>(object: I): TransactionEvent {
    const message = createBaseTransactionEvent();
    message.transaction = (object.transaction !== undefined && object.transaction !== null)
      ? TransactionEvent_Transaction.fromPartial(object.transaction)
      : undefined;
    message.network = (object.network !== undefined && object.network !== null)
      ? TransactionEvent_Network.fromPartial(object.network)
      : undefined;
    message.addresses = Object.entries(object.addresses ?? {}).reduce<{ [key: string]: boolean }>(
      (acc, [key, value]) => {
        if (value !== undefined) {
          acc[key] = globalThis.Boolean(value);
        }
        return acc;
      },
      {},
    );
    message.block = (object.block !== undefined && object.block !== null)
      ? TransactionEvent_Block.fromPartial(object.block)
      : undefined;
    message.logs = object.logs?.map((e) => TransactionEvent_Log.fromPartial(e)) || [];
    message.isContractDeployment = object.isContractDeployment ?? false;
    message.contractAddress = object.contractAddress ?? "";
    message.txAddresses = Object.entries(object.txAddresses ?? {}).reduce<{ [key: string]: boolean }>(
      (acc, [key, value]) => {
        if (value !== undefined) {
          acc[key] = globalThis.Boolean(value);
        }
        return acc;
      },
      {},
    );
    return message;
  },
};

function createBaseTransactionEvent_Network(): TransactionEvent_Network {
  return { chainId: "" };
}

export const TransactionEvent_Network = {
  encode(message: TransactionEvent_Network, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.chainId !== "") {
      writer.uint32(10).string(message.chainId);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): TransactionEvent_Network {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTransactionEvent_Network();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.chainId = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): TransactionEvent_Network {
    return { chainId: isSet(object.chainId) ? globalThis.String(object.chainId) : "" };
  },

  toJSON(message: TransactionEvent_Network): unknown {
    const obj: any = {};
    if (message.chainId !== "") {
      obj.chainId = message.chainId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<TransactionEvent_Network>, I>>(base?: I): TransactionEvent_Network {
    return TransactionEvent_Network.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TransactionEvent_Network>, I>>(object: I): TransactionEvent_Network {
    const message = createBaseTransactionEvent_Network();
    message.chainId = object.chainId ?? "";
    return message;
  },
};

function createBaseTransactionEvent_Block(): TransactionEvent_Block {
  return { blockHash: "", blockNumber: "", blockTimestamp: "", baseFeePerGas: "" };
}

export const TransactionEvent_Block = {
  encode(message: TransactionEvent_Block, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.blockHash !== "") {
      writer.uint32(10).string(message.blockHash);
    }
    if (message.blockNumber !== "") {
      writer.uint32(18).string(message.blockNumber);
    }
    if (message.blockTimestamp !== "") {
      writer.uint32(26).string(message.blockTimestamp);
    }
    if (message.baseFeePerGas !== "") {
      writer.uint32(34).string(message.baseFeePerGas);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): TransactionEvent_Block {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTransactionEvent_Block();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.blockHash = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.blockNumber = reader.string();
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.blockTimestamp = reader.string();
          continue;
        case 4:
          if (tag !== 34) {
            break;
          }

          message.baseFeePerGas = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): TransactionEvent_Block {
    return {
      blockHash: isSet(object.blockHash) ? globalThis.String(object.blockHash) : "",
      blockNumber: isSet(object.blockNumber) ? globalThis.String(object.blockNumber) : "",
      blockTimestamp: isSet(object.blockTimestamp) ? globalThis.String(object.blockTimestamp) : "",
      baseFeePerGas: isSet(object.baseFeePerGas) ? globalThis.String(object.baseFeePerGas) : "",
    };
  },

  toJSON(message: TransactionEvent_Block): unknown {
    const obj: any = {};
    if (message.blockHash !== "") {
      obj.blockHash = message.blockHash;
    }
    if (message.blockNumber !== "") {
      obj.blockNumber = message.blockNumber;
    }
    if (message.blockTimestamp !== "") {
      obj.blockTimestamp = message.blockTimestamp;
    }
    if (message.baseFeePerGas !== "") {
      obj.baseFeePerGas = message.baseFeePerGas;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<TransactionEvent_Block>, I>>(base?: I): TransactionEvent_Block {
    return TransactionEvent_Block.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TransactionEvent_Block>, I>>(object: I): TransactionEvent_Block {
    const message = createBaseTransactionEvent_Block();
    message.blockHash = object.blockHash ?? "";
    message.blockNumber = object.blockNumber ?? "";
    message.blockTimestamp = object.blockTimestamp ?? "";
    message.baseFeePerGas = object.baseFeePerGas ?? "";
    return message;
  },
};

function createBaseTransactionEvent_Transaction(): TransactionEvent_Transaction {
  return {
    type: "",
    nonce: "",
    gasPrice: "",
    gas: "",
    value: "",
    input: "",
    v: "",
    r: "",
    s: "",
    to: "",
    hash: "",
    from: "",
    maxFeePerGas: "",
    maxPriorityFeePerGas: "",
  };
}

export const TransactionEvent_Transaction = {
  encode(message: TransactionEvent_Transaction, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.type !== "") {
      writer.uint32(10).string(message.type);
    }
    if (message.nonce !== "") {
      writer.uint32(18).string(message.nonce);
    }
    if (message.gasPrice !== "") {
      writer.uint32(26).string(message.gasPrice);
    }
    if (message.gas !== "") {
      writer.uint32(34).string(message.gas);
    }
    if (message.value !== "") {
      writer.uint32(42).string(message.value);
    }
    if (message.input !== "") {
      writer.uint32(50).string(message.input);
    }
    if (message.v !== "") {
      writer.uint32(58).string(message.v);
    }
    if (message.r !== "") {
      writer.uint32(66).string(message.r);
    }
    if (message.s !== "") {
      writer.uint32(74).string(message.s);
    }
    if (message.to !== "") {
      writer.uint32(82).string(message.to);
    }
    if (message.hash !== "") {
      writer.uint32(90).string(message.hash);
    }
    if (message.from !== "") {
      writer.uint32(98).string(message.from);
    }
    if (message.maxFeePerGas !== "") {
      writer.uint32(106).string(message.maxFeePerGas);
    }
    if (message.maxPriorityFeePerGas !== "") {
      writer.uint32(114).string(message.maxPriorityFeePerGas);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): TransactionEvent_Transaction {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTransactionEvent_Transaction();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.type = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.nonce = reader.string();
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.gasPrice = reader.string();
          continue;
        case 4:
          if (tag !== 34) {
            break;
          }

          message.gas = reader.string();
          continue;
        case 5:
          if (tag !== 42) {
            break;
          }

          message.value = reader.string();
          continue;
        case 6:
          if (tag !== 50) {
            break;
          }

          message.input = reader.string();
          continue;
        case 7:
          if (tag !== 58) {
            break;
          }

          message.v = reader.string();
          continue;
        case 8:
          if (tag !== 66) {
            break;
          }

          message.r = reader.string();
          continue;
        case 9:
          if (tag !== 74) {
            break;
          }

          message.s = reader.string();
          continue;
        case 10:
          if (tag !== 82) {
            break;
          }

          message.to = reader.string();
          continue;
        case 11:
          if (tag !== 90) {
            break;
          }

          message.hash = reader.string();
          continue;
        case 12:
          if (tag !== 98) {
            break;
          }

          message.from = reader.string();
          continue;
        case 13:
          if (tag !== 106) {
            break;
          }

          message.maxFeePerGas = reader.string();
          continue;
        case 14:
          if (tag !== 114) {
            break;
          }

          message.maxPriorityFeePerGas = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): TransactionEvent_Transaction {
    return {
      type: isSet(object.type) ? globalThis.String(object.type) : "",
      nonce: isSet(object.nonce) ? globalThis.String(object.nonce) : "",
      gasPrice: isSet(object.gasPrice) ? globalThis.String(object.gasPrice) : "",
      gas: isSet(object.gas) ? globalThis.String(object.gas) : "",
      value: isSet(object.value) ? globalThis.String(object.value) : "",
      input: isSet(object.input) ? globalThis.String(object.input) : "",
      v: isSet(object.v) ? globalThis.String(object.v) : "",
      r: isSet(object.r) ? globalThis.String(object.r) : "",
      s: isSet(object.s) ? globalThis.String(object.s) : "",
      to: isSet(object.to) ? globalThis.String(object.to) : "",
      hash: isSet(object.hash) ? globalThis.String(object.hash) : "",
      from: isSet(object.from) ? globalThis.String(object.from) : "",
      maxFeePerGas: isSet(object.maxFeePerGas) ? globalThis.String(object.maxFeePerGas) : "",
      maxPriorityFeePerGas: isSet(object.maxPriorityFeePerGas) ? globalThis.String(object.maxPriorityFeePerGas) : "",
    };
  },

  toJSON(message: TransactionEvent_Transaction): unknown {
    const obj: any = {};
    if (message.type !== "") {
      obj.type = message.type;
    }
    if (message.nonce !== "") {
      obj.nonce = message.nonce;
    }
    if (message.gasPrice !== "") {
      obj.gasPrice = message.gasPrice;
    }
    if (message.gas !== "") {
      obj.gas = message.gas;
    }
    if (message.value !== "") {
      obj.value = message.value;
    }
    if (message.input !== "") {
      obj.input = message.input;
    }
    if (message.v !== "") {
      obj.v = message.v;
    }
    if (message.r !== "") {
      obj.r = message.r;
    }
    if (message.s !== "") {
      obj.s = message.s;
    }
    if (message.to !== "") {
      obj.to = message.to;
    }
    if (message.hash !== "") {
      obj.hash = message.hash;
    }
    if (message.from !== "") {
      obj.from = message.from;
    }
    if (message.maxFeePerGas !== "") {
      obj.maxFeePerGas = message.maxFeePerGas;
    }
    if (message.maxPriorityFeePerGas !== "") {
      obj.maxPriorityFeePerGas = message.maxPriorityFeePerGas;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<TransactionEvent_Transaction>, I>>(base?: I): TransactionEvent_Transaction {
    return TransactionEvent_Transaction.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TransactionEvent_Transaction>, I>>(object: I): TransactionEvent_Transaction {
    const message = createBaseTransactionEvent_Transaction();
    message.type = object.type ?? "";
    message.nonce = object.nonce ?? "";
    message.gasPrice = object.gasPrice ?? "";
    message.gas = object.gas ?? "";
    message.value = object.value ?? "";
    message.input = object.input ?? "";
    message.v = object.v ?? "";
    message.r = object.r ?? "";
    message.s = object.s ?? "";
    message.to = object.to ?? "";
    message.hash = object.hash ?? "";
    message.from = object.from ?? "";
    message.maxFeePerGas = object.maxFeePerGas ?? "";
    message.maxPriorityFeePerGas = object.maxPriorityFeePerGas ?? "";
    return message;
  },
};

function createBaseTransactionEvent_Log(): TransactionEvent_Log {
  return {
    address: "",
    topics: [],
    data: "",
    blockNumber: "",
    transactionHash: "",
    transactionIndex: "",
    blockHash: "",
    logIndex: "",
    removed: false,
  };
}

export const TransactionEvent_Log = {
  encode(message: TransactionEvent_Log, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.address !== "") {
      writer.uint32(10).string(message.address);
    }
    for (const v of message.topics) {
      writer.uint32(18).string(v!);
    }
    if (message.data !== "") {
      writer.uint32(26).string(message.data);
    }
    if (message.blockNumber !== "") {
      writer.uint32(34).string(message.blockNumber);
    }
    if (message.transactionHash !== "") {
      writer.uint32(42).string(message.transactionHash);
    }
    if (message.transactionIndex !== "") {
      writer.uint32(50).string(message.transactionIndex);
    }
    if (message.blockHash !== "") {
      writer.uint32(58).string(message.blockHash);
    }
    if (message.logIndex !== "") {
      writer.uint32(66).string(message.logIndex);
    }
    if (message.removed !== false) {
      writer.uint32(72).bool(message.removed);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): TransactionEvent_Log {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTransactionEvent_Log();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.address = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.topics.push(reader.string());
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.data = reader.string();
          continue;
        case 4:
          if (tag !== 34) {
            break;
          }

          message.blockNumber = reader.string();
          continue;
        case 5:
          if (tag !== 42) {
            break;
          }

          message.transactionHash = reader.string();
          continue;
        case 6:
          if (tag !== 50) {
            break;
          }

          message.transactionIndex = reader.string();
          continue;
        case 7:
          if (tag !== 58) {
            break;
          }

          message.blockHash = reader.string();
          continue;
        case 8:
          if (tag !== 66) {
            break;
          }

          message.logIndex = reader.string();
          continue;
        case 9:
          if (tag !== 72) {
            break;
          }

          message.removed = reader.bool();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): TransactionEvent_Log {
    return {
      address: isSet(object.address) ? globalThis.String(object.address) : "",
      topics: globalThis.Array.isArray(object?.topics) ? object.topics.map((e: any) => globalThis.String(e)) : [],
      data: isSet(object.data) ? globalThis.String(object.data) : "",
      blockNumber: isSet(object.blockNumber) ? globalThis.String(object.blockNumber) : "",
      transactionHash: isSet(object.transactionHash) ? globalThis.String(object.transactionHash) : "",
      transactionIndex: isSet(object.transactionIndex) ? globalThis.String(object.transactionIndex) : "",
      blockHash: isSet(object.blockHash) ? globalThis.String(object.blockHash) : "",
      logIndex: isSet(object.logIndex) ? globalThis.String(object.logIndex) : "",
      removed: isSet(object.removed) ? globalThis.Boolean(object.removed) : false,
    };
  },

  toJSON(message: TransactionEvent_Log): unknown {
    const obj: any = {};
    if (message.address !== "") {
      obj.address = message.address;
    }
    if (message.topics?.length) {
      obj.topics = message.topics;
    }
    if (message.data !== "") {
      obj.data = message.data;
    }
    if (message.blockNumber !== "") {
      obj.blockNumber = message.blockNumber;
    }
    if (message.transactionHash !== "") {
      obj.transactionHash = message.transactionHash;
    }
    if (message.transactionIndex !== "") {
      obj.transactionIndex = message.transactionIndex;
    }
    if (message.blockHash !== "") {
      obj.blockHash = message.blockHash;
    }
    if (message.logIndex !== "") {
      obj.logIndex = message.logIndex;
    }
    if (message.removed !== false) {
      obj.removed = message.removed;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<TransactionEvent_Log>, I>>(base?: I): TransactionEvent_Log {
    return TransactionEvent_Log.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TransactionEvent_Log>, I>>(object: I): TransactionEvent_Log {
    const message = createBaseTransactionEvent_Log();
    message.address = object.address ?? "";
    message.topics = object.topics?.map((e) => e) || [];
    message.data = object.data ?? "";
    message.blockNumber = object.blockNumber ?? "";
    message.transactionHash = object.transactionHash ?? "";
    message.transactionIndex = object.transactionIndex ?? "";
    message.blockHash = object.blockHash ?? "";
    message.logIndex = object.logIndex ?? "";
    message.removed = object.removed ?? false;
    return message;
  },
};

function createBaseTransactionEvent_AddressesEntry(): TransactionEvent_AddressesEntry {
  return { key: "", value: false };
}

export const TransactionEvent_AddressesEntry = {
  encode(message: TransactionEvent_AddressesEntry, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.key !== "") {
      writer.uint32(10).string(message.key);
    }
    if (message.value !== false) {
      writer.uint32(16).bool(message.value);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): TransactionEvent_AddressesEntry {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTransactionEvent_AddressesEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        case 2:
          if (tag !== 16) {
            break;
          }

          message.value = reader.bool();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): TransactionEvent_AddressesEntry {
    return {
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      value: isSet(object.value) ? globalThis.Boolean(object.value) : false,
    };
  },

  toJSON(message: TransactionEvent_AddressesEntry): unknown {
    const obj: any = {};
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (message.value !== false) {
      obj.value = message.value;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<TransactionEvent_AddressesEntry>, I>>(base?: I): TransactionEvent_AddressesEntry {
    return TransactionEvent_AddressesEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TransactionEvent_AddressesEntry>, I>>(
    object: I,
  ): TransactionEvent_AddressesEntry {
    const message = createBaseTransactionEvent_AddressesEntry();
    message.key = object.key ?? "";
    message.value = object.value ?? false;
    return message;
  },
};

function createBaseTransactionEvent_TxAddressesEntry(): TransactionEvent_TxAddressesEntry {
  return { key: "", value: false };
}

export const TransactionEvent_TxAddressesEntry = {
  encode(message: TransactionEvent_TxAddressesEntry, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.key !== "") {
      writer.uint32(10).string(message.key);
    }
    if (message.value !== false) {
      writer.uint32(16).bool(message.value);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): TransactionEvent_TxAddressesEntry {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTransactionEvent_TxAddressesEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        case 2:
          if (tag !== 16) {
            break;
          }

          message.value = reader.bool();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): TransactionEvent_TxAddressesEntry {
    return {
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      value: isSet(object.value) ? globalThis.Boolean(object.value) : false,
    };
  },

  toJSON(message: TransactionEvent_TxAddressesEntry): unknown {
    const obj: any = {};
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (message.value !== false) {
      obj.value = message.value;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<TransactionEvent_TxAddressesEntry>, I>>(
    base?: I,
  ): TransactionEvent_TxAddressesEntry {
    return TransactionEvent_TxAddressesEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TransactionEvent_TxAddressesEntry>, I>>(
    object: I,
  ): TransactionEvent_TxAddressesEntry {
    const message = createBaseTransactionEvent_TxAddressesEntry();
    message.key = object.key ?? "";
    message.value = object.value ?? false;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isObject(value: any): boolean {
  return typeof value === "object" && value !== null;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}
