name: Build and push gRPC files

on:
  push:
    branches:
      - main

jobs:
  generate:
    name: proto lint and generating stubs from protos
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Clean up
        run: rm -rf pkg/go

      # generate stubs
      - uses: bufbuild/buf-setup-action@v1
      - uses: bufbuild/buf-lint-action@v1
      - run: buf generate
      # compile typescript
      - uses: actions/setup-node@v4
      - run: npm install
      - run: tsc

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Autogenerate stubs from protos